Add dist/typescript.js to published files
With v3.0.2 the following error occurs; "Error: Cannot find module './typescript'"
This is most likely due to the file not being packaged and published to NPM